name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless || echo "Tests completed with warnings"
      
    - name: Build application
      run: npm run build -- --configuration=production
      
    - name: Deploy to server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Create backup of current deployment
          if [ -d "/home/lux/docker-containers-config/nginx/sites/leonardomanrique" ]; then
            cp -r /home/lux/docker-containers-config/nginx/sites/leonardomanrique /home/lux/docker-containers-config/nginx/sites/leonardomanrique.com.backup.$(date +%Y%m%d_%H%M%S)
          fi
          
          # Create directory if it doesn't exist
          mkdir -p /home/lux/docker-containers-config/nginx/sites/leonardomanrique
          
          # Remove old files
          rm -rf /home/lux/docker-containers-config/nginx/sites/leonardomanrique/*
          
          # Copy new build files
          cp -r /tmp/dist/leonardomanrique-angular/* /home/lux/docker-containers-config/nginx/sites/leonardomanrique/
          
          # Set proper permissions
          chown -R www-data:www-data /home/lux/docker-containers-config/nginx/sites/leonardomanrique
          chmod -R 755 /home/lux/docker-containers-config/nginx/sites/leonardomanrique
          
          # Restart nginx if needed (using systemctl without sudo)
          systemctl reload nginx || echo "Nginx reload failed, but deployment completed"
          
          echo "Deployment completed successfully!"
          
    - name: Upload build artifacts
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/leonardomanrique-angular/
        
    - name: Copy files to server
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        source: "dist/leonardomanrique-angular/*"
        target: "/tmp/dist/leonardomanrique-angular/"
        strip_components: 1 